entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${LE_EMAIL}"
      storage: acme.json
      httpChallenge:
        entryPoint: web
