services:
  traefik:
    command:
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:8888"
    ports:
      - "8888:8888"  # Traefik (and dashboard) on 8888 in CI
    environment:
      - CI=true
    labels:
      traefik.enable: "true"
      traefik.http.routers.llm-api.rule: Host(`llm.localhost`)
      traefik.http.routers.catchall.rule: PathPrefix(`/`)
      traefik.http.routers.catchall.entrypoints: "web"
      traefik.http.routers.catchall.service: "api@internal"
      traefik.http.routers.traefik.entrypoints: "web"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.middlewares.auth.basicauth.users: "test:$$2y$$05$$CCzkojS4y6IlVay49IP3qutwo05Q7AnTTW.TXsimWa/yvKbaRR/AC"
      traefik.http.routers.traefik.tls.certresolver: ""
      traefik.http.routers.dashboard.rule: "PathPrefix(`/dashboard`)"
      traefik.http.routers.dashboard.entrypoints: "web"
      traefik.http.routers.dashboard.service: "api@internal"
      traefik.http.routers.dashboard.middlewares: "auth"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


  llm-api:
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TEST_MODE=1
    labels:
      traefik.enable: "true"
      traefik.http.routers.llm-api.rule: "Host(`llm.localhost`)"
      traefik.http.routers.llm-api.entrypoints: "web"
      traefik.http.routers.llm-api.middlewares: "auth"
      traefik.http.services.llm-api.loadbalancer.server.port: "8080"
      traefik.http.routers.llm-api.tls.certresolver: ""
    volumes:
      - ./test-models/Meta-Llama-3-8B-Instruct.Q4_0.gguf:/home/llmuser/.cache/gpt4all/Meta-Llama-3-8B-Instruct.Q4_0.gguf

networks:
  llm-net:
