version: '3.8'

services:
  llm-node:
    build: ./llm-node
    container_name: llm-node
    ports:
      - "8000:8000"
    volumes:
      - ./llm-node/models:/app/models
    restart: unless-stopped

