version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${DASH_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./letsencrypt:/letsencrypt"
    networks:
      - llm-net
    env_file:
      - .env

  llm-api:
    build: ./llm-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.llm-api.entrypoints=websecure"
      - "traefik.http.routers.llm-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.llm-api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_USER}:${TRAEFIK_AUTH_HASH}"
    networks:
      - llm-net
    expose:
      - "8000"
    volumes:
      - ~/.cache/gpt4all:/home/llmuser/.cache/gpt4all
    env_file:
      - .env

networks:
  llm-net:
