version: '3.8'

services:
  gpt4all:
    image: runpod/gpt4all
    container_name: gpt4all
    ports:
      - "8080:8080"  # adjust port if needed
    volumes:
      - ~/.cache/gpt4all:/root/.cache/gpt4all  # cache dir, optional
    environment:
      - MODEL=gpt4all  # specify model if needed by the image
    restart: unless-stopped

