services:
  traefik:
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
    environment:
      - "CI=true"
  llm-api:
    labels:
      traefik.enable: "true"
      traefik.http.routers.llm-api.entrypoints: "web"
      traefik.http.routers.llm-api.tls.certresolver: ""
      traefik.http.routers.llm-api.rule: "Host(`llm.localhost`)"
      traefik.http.routers.llm-api.middlewares: "auth"
      traefik.http.services.llm-api.loadbalancer.server.port: "8080"
    volumes:
      - cache_data:/home/llmuser/.cache

volumes:
  cache_data:
